pub mod browser_sign_in;
pub mod chatgpt;
pub mod desktop;
mod environment;
pub mod gateway;
pub mod import;
mod model_cache;
mod paths;
mod platform;
mod process;
pub mod recording;
mod refinement;
pub mod secrets;
pub mod settings;
mod setup;
mod transcription;
